en_strings = {
    "app_title": "Weather Client",
    "menubar-file": "File",
    "menubar-file-exit": "Exit",
    "menubar-settings": "Settings",
    "menubar-settings-themes": "Themes",
    "menubar-settings-themes-light": "Light",
    "menubar-settings-themes-dark": "Dark",
    "menubar-settings-themes-console": "Console",
    "menubar-settings-themes-macos": "MacOS",
    "menubar-settings-themes-blallo": "Blallo",
    "menubar-settings-themes-shock": "Shock",
    "menubar-settings-themes-forest": "Forest",
    "menubar-settings-themes-eruption": "Eruption",
    "menubar-settings-units": "Reference System",
    "menubar-settings-units-metric": "Metric",
    "menubar-settings-units-imperial": "Imperial",
    "menubar-settings-language": "Languages",
    "menubar-settings-language-english": "English",
    "menubar-settings-language-italian": "Italian",
    "menubar-help": "Help",
    "menubar-help-issue": "Present a problem",
    "menubar-help-developer": "Contact the developer",
    "menubar-help-feedback": "Send a feedback",
    "menubar-help_about": "About",
    "reload_button": "Reload",
    "search_button": "Search",
    "metric_temp_symbol": "°C",
    "imperial_temp_symbol": "°F",
    "max_temp": "Max temperature",
    "min_temp": "Min temperature",
    "humidity": "Humidity",
    "clouds": "Clouds",
    "precipitations": "Precipitations",
    "no_precipitations": "Absents",
    "rain": "Rain",
    "snow": "Snow",
    "wind": "Wind",
    "wind_speed_metric": "km/h",
    "wind_speed_imperial": "MPH",
    "last_updated": "Last Updated",
    "info_title": "Weather Client Info",
    "info_name": "Weather Client",
    "info_api_usage": "Uses API from",
    "info_icons_by": "Icons by",
    "info_changenotes": "Changenotes",
    "info_close_button": "Close",
}