it_strings = {
    "app_title": "Meteo",
    "menubar-file": "File",
    "menubar-file-exit": "Esci",
    "menubar-settings": "Impostazioni",
    "menubar-settings-themes": "Temi",
    "menubar-settings-themes-light": "Chiaro",
    "menubar-settings-themes-dark": "Scuro",
    "menubar-settings-themes-console": "Console",
    "menubar-settings-themes-macos": "MacOS",
    "menubar-settings-themes-blallo": "Blallo",
    "menubar-settings-themes-shock": "Shock",
    "menubar-settings-themes-forest": "Foresta",
    "menubar-settings-themes-eruption": "Eruzione",
    "menubar-settings-units": "Sistema di riferimento",
    "menubar-settings-units-metric": "Metrico",
    "menubar-settings-units-imperial": "Imperiale",
    "menubar-settings-language": "Lingue",
    "menubar-settings-language-english": "Inglese",
    "menubar-settings-language-italian": "Italiano",
    "menubar-help": "Help",
    "menubar-help-issue": "Presenta un problema",
    "menubar-help-developer": "Contatta lo sviluppatore",
    "menubar-help-feedback": "Invia un feedback",
    "menubar-help_about": "About",
    "reload_button": "Ricarica",
    "search_button": "Cerca",
    "metric_temp_symbol": "°C",
    "imperial_temp_symbol": "°F",
    "max_temp": "Temperatura max",
    "min_temp": "Temperatura min",
    "humidity": "Umidità",
    "clouds": "Nuvole",
    "precipitations": "Precipitazioni",
    "no_precipitations": "Assenti",
    "rain": "Pioggia",
    "snow": "Neve",
    "wind": "Vento",
    "wind_speed_metric": "km/h",
    "wind_speed_imperial": "MPH",
    "last_updated": "Ultimo Aggiornamento",
    "info_title": "Info Client Meteo",
    "info_name": "Client Meteo",
    "info_api_usage": "Usa l'API di",
    "info_icons_by": "Icone di",
    "info_changenotes": "Note di Rilascio",
    "info_close_button": "Chiudi",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

}